import pandas as pd
path = input("Enter the path of the csv file (or) File name if it is in the same working directory")
data = pd.read_csv(path)
stat = data.isnull().sum()
print("Before Removing")
print(stat)
print(data.shape)
print("----------------------")
datafile = data.dropna()
print("After Removing")
print(datafile)
print(datafile.shape)
print("----------------------")
save_name = input("Enter a new name for the file(With the required file extension)")
datafile.to_csv(save_name)